version: '3'
services:
  activemq:
    container_name: 'activemq'
    image: freekode/activemq
    ports:
      - '61616:61616'
      - '8161:8161'
  platform-binance:
    container_name: 'platform-binance'
    image: docker.pkg.github.com/cryptocurrency-robot/platform-binance/platform-binance:latest
    depends_on:
      - activemq
    ports:
      - '8081:8080'
    environment:
      - BROKER_URL=tcp://crypto-bot-activemq:61616
      - BINANCE_API_KEY=test-key
      - BINANCE_API_SECRET=test-secret
